// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zempgfcqkogdyisrxvlk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplbXBnZmNxa29nZHlpc3J4dmxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTQxNTcsImV4cCI6MjA3MDY3MDE1N30.7uesetwJLA-w0XmpQ_5PlD40yv9E-SnE7xsLwu_18Iw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});